apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts # which port we actually need to expose
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # expose to outside world
      targetPort: 4000 # expose to NodePort
